# Generated by Django 5.1.7 on 2025-03-31 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0002_sale_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.IntegerField()),
                ('payment_frequency', models.CharField(max_length=15)),
                ('total_with_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_pending', models.IntegerField()),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_payment_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.customer')),
            ],
        ),
    ]
