# Generated by Django 5.1.7 on 2025-04-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0003_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_id',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_acc_no',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
