# Generated by Django 5.1.7 on 2025-04-01 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0004_remove_loan_loan_id_loan_loan_acc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_seq', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('Payment_status', models.CharField(max_length=15)),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.loan')),
            ],
        ),
    ]
