# Generated by Django 5.1.7 on 2025-04-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0005_loanbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_acc_no',
            new_name='loan_accno',
        ),
        migrations.RenameField(
            model_name='loanbill',
            old_name='loan_accno',
            new_name='loan_acc',
        ),
    ]
