# Generated by Django 5.1.7 on 2025-04-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0006_rename_loan_acc_no_loan_loan_accno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_accno',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
