# Generated by Django 5.1.7 on 2025-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0007_alter_loan_loan_accno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbill',
            name='Payment_status',
        ),
        migrations.AddField(
            model_name='loanbill',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
