# Generated by Django 5.1.7 on 2025-04-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0008_remove_loanbill_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbill',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanbill',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
