# Generated by Django 5.1.7 on 2025-04-03 12:58

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0009_alter_loanbill_late_fee_alter_loanbill_paid_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_mph', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('Purchase_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingModule.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_seq', models.IntegerField(default=1)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='BillingModule.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_products',
            field=models.ManyToManyField(through='BillingModule.PurchaseItem', to='BillingModule.item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.seller'),
        ),
    ]
