# Generated by Django 5.1.7 on 2025-04-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0010_purchasepayment_seller_purchase_purchaseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Purchase_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
