# Generated by Django 5.1.7 on 2025-04-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0011_seller_address_alter_purchase_purchase_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBill',
            fields=[
                ('bill_year', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_seq', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bill',
            new_name='PurchaseBill',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Purchase_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
