# Generated by Django 5.1.7 on 2025-04-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0012_salebill_rename_bill_purchasebill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='payment',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingModule.purchasepayment'),
        ),
    ]
