# Generated by Django 5.1.7 on 2025-04-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0013_remove_purchase_payment_purchase_purchase_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='payment',
            new_name='sale_payment',
        ),
    ]
