# Generated by Django 5.1.7 on 2025-04-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0014_rename_payment_sale_sale_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_payment',
            new_name='payment',
        ),
    ]
