# Generated by Django 5.1.7 on 2025-04-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0015_rename_sale_payment_sale_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Purchase_id',
            new_name='purchase_id',
        ),
    ]
