# Generated by Django 5.1.7 on 2025-04-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0016_rename_purchase_id_purchase_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_seq',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_seq',
            field=models.IntegerField(default=1),
        ),
    ]
