# Generated by Django 5.1.7 on 2025-04-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0017_purchase_purchase_seq_sale_sale_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
