# Generated by Django 5.1.7 on 2025-04-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0018_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
