# Generated by Django 5.1.7 on 2025-04-10 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0019_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='total_with_interest',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='advance_amount',
            new_name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='due_pending',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
