# Generated by Django 5.1.7 on 2025-04-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0020_rename_total_with_interest_loan_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanJournal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATED', 'Loan Issued'), ('PAYMENT', 'Payment Made'), ('UPDATED', 'Loan Updated'), ('CLOSED', 'Loan Closed')], max_length=20)),
                ('description', models.TextField()),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='BillingModule.loan')),
            ],
        ),
    ]
