# Generated by Django 5.1.7 on 2025-04-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0022_loanjournal_balance_amount_loanjournal_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbill',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
