# Generated by Django 5.1.7 on 2025-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0023_loanbill_balance_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbill',
            name='balance_amount',
        ),
        migrations.AddField(
            model_name='loanbill',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanbill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
