# Generated by Django 5.1.7 on 2025-04-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0024_remove_loanbill_balance_amount_loanbill_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
