# Generated by Django 5.1.7 on 2025-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0025_alter_loanbill_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='next_payment_date',
            new_name='next_pay_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='payment_frequency',
            new_name='payment_freq',
        ),
        migrations.AddField(
            model_name='loan',
            name='bal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
