# Generated by Django 5.1.7 on 2025-04-12 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0026_rename_next_payment_date_loan_next_pay_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbill',
            name='payment_status',
        ),
        migrations.CreateModel(
            name='GlHist',
            fields=[
                ('trans_seq', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trans_command', models.TextField()),
                ('credit', models.BooleanField(default=False)),
                ('debit', models.BooleanField(default=False)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillingModule.loan')),
            ],
        ),
        migrations.DeleteModel(
            name='LoanJournal',
        ),
    ]
