# Generated by Django 5.1.7 on 2025-04-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingModule', '0027_remove_loanbill_payment_status_glhist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanJournal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATED', 'Loan Issued'), ('PAYMENT', 'Payment Made'), ('UPDATED', 'Loan Updated'), ('CLOSED', 'Loan Closed')], max_length=20)),
                ('description', models.TextField()),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='BillingModule.loan')),
            ],
        ),
    ]
